# Site settings
title: Declan Dawson Taylor
email: declan.taylor@rogers.com
description: The Jekyll version of the Spectral theme by HTML5 UP.
baseurl: "/spectral-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/declan-taylor
gitlab_url: 
googleplus_url:
instagram_url: https://www.instagram.com/declan.dawson/
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Declan_D_Taylor

# Build settings
markdown: kramdown
